#!/usr/bin/env python3
"""cm3_html.py — self-contained interactive CM3 explorer.

Renders the SAME model that `cm3_by_product.compute()` produces into a single
HTML file with inline CSS + JS and the data embedded as JSON (zero external
refs). The embedded JS recomputes CM1/CM2/CM3 and re-bands every product from
tunable controls (shipping %, processing %, fixed costs, and the five band
cutoffs) — byte-identical to the Python model at the default parameters.

Per-product COGS% is resolved once by the Python model (Title -> Vendor ->
Store avg -> Input) and embedded per row; the explorer tunes the shared
ship/proc/fixed assumptions and the band cutoffs, never the per-product COGS.

Stdlib only at import time. The public entry point is
`build_html(ctx, period, currency, path)`.

Charts are DECLARED in `CHARTS` below and GENERATED by the vendored chart
module (`_charts/charts.py`, a byte-identical copy of the shared render
toolkit's chart layer, drift-guarded by tests/test_cm3.py) — never
hand-authored. One declaration drives both render paths: static SVG at build
time (vl-convert, md report + tuner widget) and the live explorer charts
(vendored Vega/Vega-Lite runtime in `_charts/vendor/`), which re-derive from
the same recomputed rows as the table on every control change.
"""
from __future__ import annotations

import datetime as _dt
import json
import os
import re
import sys
from typing import Any

# Vendored chart module (stdlib at import; vl-convert lazy-loads on static render).
_CHARTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_charts")
if _CHARTS_DIR not in sys.path:
    sys.path.insert(0, _CHARTS_DIR)
import charts as _charts  # noqa: E402

_DEFAULT_CUTOFFS = {"band_exc": 0.10, "band_high": 0.05, "band_avg": 0.00, "band_low": -0.25}

# ─── Chart declarations (generated, never authored) ───────────────────────────
# Band colors are the explorer's own band identity — the text color of each
# .b-<Band> badge class in _TEMPLATE (the backgrounds are pale tints; the text
# color is the saturated per-band identifier, post the HiveMind-teal rebrand).
# tests/test_cm3.py asserts this dict stays equal to the template CSS, with
# var() references resolved through :root.
BAND_ORDER = ["Excellent", "High", "Average", "Low", "Poor", "Inactive"]
BAND_COLORS = {
    "Excellent": "#1f6b46",
    "High": "#0f5a4a",
    "Average": "#0f4a52",
    "Low": "#7a4a0b",
    "Poor": "#a3261f",
    "Inactive": "#3c4350",
}
_BAND_SCALE = {"domain": BAND_ORDER, "range": [BAND_COLORS[b] for b in BAND_ORDER]}

# Fields referenced here must exist BOTH in the Python-side chart rows
# (chart_rows() below: the embedded row dicts augmented with the model's
# cm3/cm3_pct/band) AND in the explorer's live rowsComputed() rows. All
# aggregation lives in the Vega-Lite `transform` array so the static SVGs and
# the live charts share one definition verbatim. Never reference the
# provenance `generated` timestamp in a chart.
CHARTS = [
    {
        "id": "revenue_by_band",
        "title": "Revenue by CM3 band",
        "mark": {"type": "bar"},
        "transform": [
            {"aggregate": [{"op": "sum", "field": "rev", "as": "revenue"}],
             "groupby": ["band"]},
        ],
        "encoding": {
            "x": {"field": "band", "type": "nominal", "title": "CM3 band",
                  "sort": BAND_ORDER, "axis": {"labelAngle": 0}},
            "y": {"field": "revenue", "type": "quantitative", "title": "Revenue"},
            "color": {"field": "band", "type": "nominal", "legend": None,
                      "scale": _BAND_SCALE},
        },
        "width": 560, "height": 220,
        "md": True,
        "widget": True,
    },
    {
        "id": "revenue_cm3_scatter",
        "title": "Revenue vs CM3 % per product",
        "mark": {"type": "point", "size": 70, "filled": True, "opacity": 0.82},
        "transform": [
            {"filter": "datum.cm3_pct != null"},
        ],
        "encoding": {
            "x": {"field": "rev", "type": "quantitative", "title": "Revenue",
                  "scale": {"nice": True, "padding": 16}},
            "y": {"field": "cm3_pct", "type": "quantitative", "title": "CM3 %",
                  "axis": {"format": ".0%"}, "scale": {"nice": True, "padding": 16}},
            "color": {"field": "band", "type": "nominal", "title": "Band",
                      "scale": _BAND_SCALE,
                      "legend": {"orient": "bottom", "columns": 6, "symbolLimit": 6}},
        },
        "width": 560, "height": 260,
        "md": True,
        "widget": False,
    },
]


def chart_rows(ctx: dict) -> list:
    """Rows the static chart render consumes: the explorer's embedded row dicts
    augmented with the Python model's computed cm3/cm3_pct/band at the default
    params — the same augmentation the live JS applies via rowsComputed().
    Model row order is preserved (deterministic)."""
    products = ctx["products"]
    rows = []
    for p in products:
        rows.append({
            "t": p.title,
            "camp": p.campaign or "(no campaign)",
            "ven": p.vendor or "",
            "src": p.cogs_source,
            "impr": p.impr,
            "clicks": p.clicks,
            "cost": p.cost,
            "conv": p.conv,
            "rev": p.conv_value,
            "cogs": p.cogs_pct,
            "cm1": p.cm1,
            "cm2": p.cm2,
            "cm3": p.cm3,
            "cm3_pct": p.cm3_pct,
            "band": p.band,
        })
    return rows


def render_static_charts(ctx: dict, *, only: str | None = None) -> list:
    """Render the declared charts to SVG at the model's default params via the
    vendored chart module. Returns [(chart_id, title, svg), ...]. Hard-fails
    (SystemExit 2) with a clear message if vl-convert-python is missing."""
    return _charts.render_spec_charts({"rows": chart_rows(ctx)}, {"charts": CHARTS}, only=only)


def _cutoffs(ctx: dict) -> dict:
    """Resolved band cutoffs as {exc,high,avg,low} fractions, from ctx or defaults."""
    c = ctx.get("cutoffs") or {}
    inp = ctx.get("inputs") or {}
    g = lambda k: float(c.get(k, inp.get(k, _DEFAULT_CUTOFFS[k])))
    return {"exc": g("band_exc"), "high": g("band_high"), "avg": g("band_avg"), "low": g("band_low")}


def _vendor_cogs_map(ctx: dict) -> dict:
    """Resolved per-vendor COGS% exactly as build_vendor_rollup shows it:
    the Shopify-lookup value if present, else the blanket fallback. Keyed by
    the vendor's display name (first-seen order preserved)."""
    look = ctx.get("cogs_look")
    fallback = ctx.get("fallback_cogs")
    if fallback is None:
        fallback = float((ctx.get("inputs") or {}).get("cogs_pct", 0)) / 100.0
    out: dict = {}
    for p in ctx["products"]:
        if p.vendor and p.vendor not in out:
            vc = look.by_vendor.get(p.vendor.lower().strip()) if look is not None else None
            out[p.vendor] = vc if vc is not None else fallback
    return out


def _model(ctx: dict, period: str | None, currency: str) -> dict:
    products = ctx["products"]
    total_rev = sum(p.conv_value for p in products)
    rows = [
        {
            "t": p.title,
            "camp": p.campaign or "(no campaign)",
            "catL": list(p.cat),      # 5 category levels ('' where absent)
            "ptL": list(p.ptype),     # 5 product-type levels
            "ven": p.vendor or "",
            "src": p.cogs_source,
            "impr": p.impr,
            "clicks": p.clicks,
            "cost": p.cost,
            "conv": p.conv,
            "rev": p.conv_value,
            "cogs": p.cogs_pct,
        }
        for p in products
    ]
    inp = ctx["inputs"]
    return {
        "provenance": {
            "period": period or "unknown",
            "currency": currency,
            "generated": _dt.datetime.now().isoformat(timespec="seconds"),
            "n": len(rows),
            "cogs_mode": "Per-product (Shopify GP CSV)" if ctx.get("cogs_look") else f"{inp['cogs_pct']}% blanket",
        },
        "params": {
            "ship": inp["ship_pct"] / 100.0,
            "proc": inp["proc_pct"] / 100.0,
            "fixed": float(inp.get("fixed_costs") or 0),
            "total_rev": total_rev,
            "cutoffs": _cutoffs(ctx),
        },
        "vcogs": _vendor_cogs_map(ctx),
        "srcmix": dict(ctx.get("cogs_source_counts") or {}),
        "rows": rows,
    }


_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CM3 by product — explorer</title>
<style>
/* Full Clickt brand token set, mirrored from google-ads-audit/scripts/audit_html.py
   (neutrals, teal family, --lime/--purple/--ember division accents, semantic
   --pass/--fail/--flag/--na). CM3's legacy tokens (--cloud/--mist/--surface/
   --tint/--sage/--ink-2/--accent-soft/--line-strong/--dim) are reconciled onto
   the same palette so the whole explorer flips with one theme mechanism.
   BAND CONTRACT: the .b-<band> badge text colors are literal light hex (below);
   --teal-deep (#0F4A52) is Average's identity and is NEVER redefined in a dark
   block, so tests/test_cm3.py's light-hex parse stays valid. Dark badge legibility
   is provided by theme-scoped descendant overrides, never by mutating those vars. */
:root{
  --ink:#0B0F0E; --ink-2:#14191A; --offwhite:#EEF1F3; --slate:#5C6470; --dim:#5C6470;
  --card:#FFFFFF; --bg:#F3F4F6; --cloud:#F3F4F6; --mist:#E7EAED;
  --line:rgba(11,15,14,.10); --line-2:rgba(11,15,14,.06); --line-strong:rgba(11,15,14,.18);
  --teal:#1F7A82; --teal-deep:#0F4A52; --abyss:#07262B; --teal-100:#97C4BD; --tint:#97C4BD;
  --sage:#5BA89A; --surface:#DAE9E6;
  --lime:#B4E01F; --lime-700:#3F5410; --lime-50:#EEF7D2;
  --purple:#897B9E; --purple-700:#2B2236; --ember:#F86B3C;
  --pass:var(--lime-700); --pass-bg:var(--lime-50);
  --flag:#8A6D00; --flag-bg:#FBF0CC;
  --fail:#B23A16; --fail-bg:#FBE1D8;
  --na:var(--slate); --na-bg:#ECEEF0;
  --chrome:var(--abyss); --accent:#1F7A82; --accent-soft:rgba(31,122,130,.12);
  --accent-ink:var(--teal-deep);
  --shadow:0 1px 2px rgba(11,15,14,.06),0 8px 24px rgba(11,15,14,.06);
  --font:"Inter",system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  --mono:"JetBrains Mono",ui-monospace,SFMono-Regular,Menlo,Consolas,"Liberation Mono",monospace;
}
/* Dark: OS-preference default (JS-off path) — do NOT redefine --teal-deep here. */
@media(prefers-color-scheme:dark){:root{
  --ink:#EEF1F3; --offwhite:#0B0F0E; --slate:#9AA4AE; --dim:#9AA4AE;
  --card:#0F1A1C; --bg:#081113; --cloud:#0C1618; --mist:#1B2A2C;
  --line:rgba(238,241,243,.12); --line-2:rgba(238,241,243,.07); --line-strong:rgba(238,241,243,.22);
  --tint:#97C4BD; --sage:#5BA89A; --surface:rgba(31,122,130,.22);
  --accent:#3FA0A8; --accent-soft:rgba(63,160,168,.18); --accent-ink:#8FD4DA;
  --pass:#B4E01F; --pass-bg:rgba(180,224,31,.12);
  --flag:#E7C453; --flag-bg:rgba(231,196,83,.12);
  --fail:#FF8A64; --fail-bg:rgba(248,107,60,.14);
  --na:#9AA4AE; --na-bg:rgba(154,164,174,.14);
  --shadow:0 1px 2px rgba(0,0,0,.4),0 8px 24px rgba(0,0,0,.4);
}}
/* Explicit toggle overrides (win over the media query in both directions). */
:root[data-theme="dark"]{
  --ink:#EEF1F3; --offwhite:#0B0F0E; --slate:#9AA4AE; --dim:#9AA4AE;
  --card:#0F1A1C; --bg:#081113; --cloud:#0C1618; --mist:#1B2A2C;
  --line:rgba(238,241,243,.12); --line-2:rgba(238,241,243,.07); --line-strong:rgba(238,241,243,.22);
  --tint:#97C4BD; --sage:#5BA89A; --surface:rgba(31,122,130,.22);
  --accent:#3FA0A8; --accent-soft:rgba(63,160,168,.18); --accent-ink:#8FD4DA;
  --pass:#B4E01F; --pass-bg:rgba(180,224,31,.12);
  --flag:#E7C453; --flag-bg:rgba(231,196,83,.12);
  --fail:#FF8A64; --fail-bg:rgba(248,107,60,.14);
  --na:#9AA4AE; --na-bg:rgba(154,164,174,.14);
  --shadow:0 1px 2px rgba(0,0,0,.4),0 8px 24px rgba(0,0,0,.4);
}
:root[data-theme="light"]{
  --ink:#0B0F0E; --offwhite:#EEF1F3; --slate:#5C6470; --dim:#5C6470;
  --card:#FFFFFF; --bg:#F3F4F6; --cloud:#F3F4F6; --mist:#E7EAED;
  --line:rgba(11,15,14,.10); --line-strong:rgba(11,15,14,.18);
  --tint:#97C4BD; --surface:#DAE9E6;
  --accent:#1F7A82; --accent-soft:rgba(31,122,130,.12); --accent-ink:var(--teal-deep);
  --pass:var(--lime-700); --pass-bg:var(--lime-50); --flag:#8A6D00; --flag-bg:#FBF0CC;
  --fail:#B23A16; --fail-bg:#FBE1D8; --na:var(--slate); --na-bg:#ECEEF0;
  --shadow:0 1px 2px rgba(11,15,14,.06),0 8px 24px rgba(11,15,14,.06);
}
*{box-sizing:border-box}
body{margin:0;background:var(--cloud);color:var(--ink);font:14px/1.55 var(--font);-webkit-font-smoothing:antialiased}
input,select,button{accent-color:var(--teal)}
header{background:linear-gradient(160deg,var(--abyss),var(--teal-deep));color:#EEF1F3;padding:clamp(18px,3.5vw,30px) clamp(16px,4vw,34px)}
.hdr{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;max-width:1240px;margin:0 auto}
.hdr-main{min-width:0}
header h1{font-size:19px;margin:0 0 8px;font-weight:700;letter-spacing:-.02em}
.prov{font-family:var(--mono);font-size:11px;letter-spacing:.02em;color:var(--tint);margin:0}
.themebtn{flex:none;font:inherit;font-size:12px;font-weight:600;display:inline-flex;align-items:center;gap:7px;padding:7px 13px;border-radius:999px;border:1px solid rgba(238,241,243,.30);background:rgba(238,241,243,.08);color:#EEF1F3;cursor:pointer;transition:background .15s,border-color .15s}
.themebtn:hover{background:rgba(238,241,243,.16);border-color:rgba(238,241,243,.55)}
.themebtn:focus-visible{outline:2px solid var(--tint);outline-offset:2px}
.themebtn .ico{font-size:13px;line-height:1}
.wrap{width:100%;max-width:1240px;margin:0 auto;padding:18px clamp(14px,4vw,28px) 56px}
.grid{display:grid;grid-template-columns:minmax(0,1fr);gap:16px;align-items:start}
.grid>*{min-width:0}
@media(min-width:960px){.grid{grid-template-columns:minmax(300px,340px) minmax(0,1fr)}}
.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px 18px;margin-bottom:16px;box-shadow:var(--shadow)}
.card h2{font-family:var(--mono);font-size:11px;margin:0 0 14px;font-weight:500;letter-spacing:.08em;text-transform:uppercase;color:var(--slate)}
.ctls{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px 18px;align-items:start}
.ctl{margin:0}
.ctl label{display:flex;justify-content:space-between;align-items:center;gap:8px;font-size:13px;font-weight:600;margin:0 0 6px}
.ctl label span{display:inline-block;min-width:2.6em;padding:1px 8px;border-radius:999px;background:var(--accent-soft);color:var(--accent-ink);font-weight:600;font-size:12px;font-variant-numeric:tabular-nums;text-align:center;line-height:1.5}
.ctl input[type=range]{-webkit-appearance:none;appearance:none;width:100%;height:18px;margin:4px 0;background:transparent;cursor:pointer}
.ctl input[type=range]::-webkit-slider-runnable-track{height:6px;border-radius:999px;background:linear-gradient(90deg,var(--teal) 0 calc(var(--p,0)*1%),var(--mist) calc(var(--p,0)*1%) 100%)}
.ctl input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;appearance:none;width:16px;height:16px;margin-top:-5px;border-radius:50%;background:var(--card);border:2px solid var(--teal);box-shadow:0 1px 2px rgba(11,15,14,.3);transition:box-shadow .15s,transform .15s}
.ctl input[type=range]::-moz-range-track{height:6px;border-radius:999px;background:var(--mist)}
.ctl input[type=range]::-moz-range-progress{height:6px;border-radius:999px;background:var(--teal)}
.ctl input[type=range]::-moz-range-thumb{width:16px;height:16px;border:2px solid var(--teal);border-radius:50%;background:var(--card);box-shadow:0 1px 2px rgba(11,15,14,.3);transition:box-shadow .15s,transform .15s}
.ctl input[type=range]:hover::-webkit-slider-thumb{transform:scale(1.08)}.ctl input[type=range]:hover::-moz-range-thumb{transform:scale(1.08)}
.ctl input[type=range]:active::-webkit-slider-thumb{transform:scale(1.12)}.ctl input[type=range]:active::-moz-range-thumb{transform:scale(1.12)}
.ctl input[type=range]:focus{outline:none}
.ctl input[type=range]:focus-visible::-webkit-slider-thumb{box-shadow:0 0 0 4px rgba(31,122,130,.3)}
.ctl input[type=range]:focus-visible::-moz-range-thumb{box-shadow:0 0 0 4px rgba(31,122,130,.3)}
.ctl input[type=number]{width:100%;height:32px;padding:0 9px;border:1px solid var(--line-strong);border-radius:8px;background:var(--card);color:var(--ink);font:inherit;font-size:13px;line-height:32px;font-variant-numeric:tabular-nums;transition:border-color .15s,box-shadow .15s}
.ctl input[type=number]:focus{outline:none;border-color:var(--teal);box-shadow:0 0 0 3px rgba(31,122,130,.18)}
:focus-visible{outline:2px solid var(--teal);outline-offset:2px}
th:focus-visible{outline-offset:-2px}
.kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px;margin:0 0 16px}
.kpi{background:var(--cloud);border:1px solid var(--line);border-radius:10px;padding:11px 13px}
.kpi .l{font-family:var(--mono);font-size:10px;color:var(--slate);text-transform:uppercase;letter-spacing:.05em}
.kpi .v{font-size:21px;font-weight:700;margin-top:3px;font-variant-numeric:tabular-nums;color:var(--ink)}
table{width:100%;border-collapse:collapse;font-size:12.5px;background:var(--card)}
th,td{padding:7px 9px;border-bottom:1px solid var(--line);text-align:right;white-space:nowrap}
th{position:sticky;top:0;background:var(--cloud);cursor:pointer;font-family:var(--mono);font-size:10.5px;text-transform:uppercase;letter-spacing:.04em;color:var(--slate);font-weight:500;z-index:1}
td.l,th.l{text-align:left;white-space:normal}
td.l:first-child{min-width:150px;max-width:280px}
.tablewrap{max-height:560px;overflow:auto;border:1px solid var(--line);border-radius:10px}
.bands{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 4px}
.badge{display:inline-block;padding:2px 9px;border-radius:999px;font-size:11.5px;font-weight:600}
.b-Excellent{background:rgba(47,122,82,.16);color:#1f6b46}.b-High{background:rgba(91,168,154,.24);color:#0f5a4a}
.b-Average{background:var(--surface);color:var(--teal-deep)}.b-Low{background:#f6ead2;color:#7a4a0b}
.b-Poor{background:#fbe9e7;color:#a3261f}.b-Inactive{background:var(--mist);color:#3c4350}
/* Dark badge legibility — theme-scoped descendant overrides only (the base rules
   above keep their literal light hex, which the band-color test parses). The four
   layers cover: OS-dark w/ no JS (@media), forced dark, and forced light on a dark OS. */
@media(prefers-color-scheme:dark){
.b-Excellent{background:rgba(47,122,82,.26);color:#84DCA5}.b-High{background:rgba(91,168,154,.26);color:#7BD3BF}
.b-Average{background:rgba(31,122,130,.26);color:#7EC6CE}.b-Low{background:rgba(160,110,20,.26);color:#E3B85C}
.b-Poor{background:rgba(163,38,31,.28);color:#F3897D}.b-Inactive{background:rgba(154,164,174,.20);color:#AEB7C2}
}
:root[data-theme="dark"] .b-Excellent{background:rgba(47,122,82,.26);color:#84DCA5}
:root[data-theme="dark"] .b-High{background:rgba(91,168,154,.26);color:#7BD3BF}
:root[data-theme="dark"] .b-Average{background:rgba(31,122,130,.26);color:#7EC6CE}
:root[data-theme="dark"] .b-Low{background:rgba(160,110,20,.26);color:#E3B85C}
:root[data-theme="dark"] .b-Poor{background:rgba(163,38,31,.28);color:#F3897D}
:root[data-theme="dark"] .b-Inactive{background:rgba(154,164,174,.20);color:#AEB7C2}
:root[data-theme="light"] .b-Excellent{background:rgba(47,122,82,.16);color:#1f6b46}
:root[data-theme="light"] .b-High{background:rgba(91,168,154,.24);color:#0f5a4a}
:root[data-theme="light"] .b-Average{background:var(--surface);color:var(--teal-deep)}
:root[data-theme="light"] .b-Low{background:#f6ead2;color:#7a4a0b}
:root[data-theme="light"] .b-Poor{background:#fbe9e7;color:#a3261f}
:root[data-theme="light"] .b-Inactive{background:var(--mist);color:#3c4350}
.bandstat{border:1px solid var(--line);border-radius:8px;padding:6px 10px;font-size:13px;display:flex;align-items:center;gap:6px}
.ktable{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:8px}
.kr{display:flex;justify-content:space-between;gap:8px;padding:7px 11px;background:var(--cloud);border:1px solid var(--line);border-radius:8px;font-variant-numeric:tabular-nums}
.kr em{font-style:normal;color:var(--slate)}.kr b{font-weight:700}
.pillnav{display:flex;flex-wrap:wrap;gap:6px;margin:0 0 14px}
.pill{font:inherit;font-size:12px;font-weight:600;padding:5px 13px;border-radius:999px;border:1px solid var(--line-strong);background:var(--card);color:var(--slate);cursor:pointer;transition:background .15s,color .15s,border-color .15s}
.pill:hover{border-color:var(--teal)}
.pill.on{background:var(--accent-soft);color:var(--accent-ink);border-color:var(--teal)}
.rolltbl{margin:0 0 18px}.rolltbl:last-child{margin-bottom:0}
.rolltitle{font-family:var(--mono);font-size:11px;letter-spacing:.04em;color:var(--slate);text-transform:uppercase;margin:0 0 6px}
.mrow{display:flex;justify-content:space-between;gap:14px;padding:7px 0;border-bottom:1px solid var(--line)}
.mrow:last-of-type{border-bottom:none}
.mrow em{font-style:normal;color:var(--slate)}.mrow b{font-weight:600;text-align:right}
.pivotctls{display:flex;flex-wrap:wrap;gap:10px 16px;margin:0 0 14px;align-items:flex-end}
.pivotsel{display:flex;flex-direction:column;gap:5px;font-family:var(--mono);font-size:10.5px;font-weight:500;letter-spacing:.04em;text-transform:uppercase;color:var(--slate)}
.pivotsel select{font:inherit;font-family:var(--font);font-size:13px;font-weight:500;letter-spacing:0;text-transform:none;color:var(--ink);padding:7px 10px;border:1px solid var(--line-strong);border-radius:8px;background:var(--card);cursor:pointer;min-width:150px}
.pivotsel select:focus{outline:none;border-color:var(--teal);box-shadow:0 0 0 3px rgba(31,122,130,.18)}
.pivttbl th.rowhdr,.pivttbl td.rowhdr{text-align:left;white-space:nowrap;position:sticky;left:0;background:var(--cloud);z-index:1}
.pivttbl th.rowhdr{z-index:2}
.pivttbl td.dim{color:var(--slate);opacity:.5}
.pivttbl td.totcol,.pivttbl th.totcol{font-weight:700;background:var(--cloud)}
.pivttbl tr.totrow td{font-weight:700;background:var(--cloud);border-top:1px solid var(--line-strong)}
.muted{color:var(--slate);font-size:12px;margin:12px 0 0;line-height:1.6}
footer{color:var(--slate);font-size:12px;margin-top:22px}
@media(prefers-reduced-motion:reduce){*{transition:none!important}}
</style>
</head>
<body>
<header>
<div class="hdr">
<div class="hdr-main">
<h1>CM3 by product — explorer</h1>
<div class="prov" id="prov"></div>
</div>
<button type="button" class="themebtn" id="themeToggle" aria-label="Toggle dark mode"><span class="ico" id="themeIco">◐</span><span id="themeTxt">Theme</span></button>
</div>
</header>
<div class="wrap">
<div class="grid">
<div>
<div class="card">
<h2>Assumptions</h2>
<div class="ctls">
<div class="ctl"><label>Shipping % <span id="shipv"></span></label><input type="range" id="ship" min="0" max="60" step="0.5"></div>
<div class="ctl"><label>Processing % <span id="procv"></span></label><input type="range" id="proc" min="0" max="15" step="0.1"></div>
<div class="ctl"><label>Fixed costs (allocated by revenue share)</label><input type="number" id="fixed" min="0" step="100"></div>
</div>
<h2 style="margin-top:18px">Band cutoffs (CM3%)</h2>
<div class="ctls">
<div class="ctl"><label>Excellent ≥ <span id="excv"></span></label><input type="range" id="exc" min="0" max="40" step="0.5"></div>
<div class="ctl"><label>High ≥ <span id="highv"></span></label><input type="range" id="high" min="0" max="30" step="0.5"></div>
<div class="ctl"><label>Average ≥ <span id="avgv"></span></label><input type="range" id="avg" min="-10" max="20" step="0.5"></div>
<div class="ctl"><label>Low ≥ <span id="lowv"></span></label><input type="range" id="low" min="-60" max="10" step="0.5"></div>
</div>
</div>
</div>
<div>
<div class="kpis" id="kpis"></div>
<div class="card" style="margin-bottom:14px"><h2>Top-line KPIs (live)</h2><div class="ktable" id="sumkpis"></div></div>
<div class="card" style="margin-bottom:14px"><h2>By band (live)</h2><div id="bands"></div></div>
<div class="card" style="margin-bottom:14px" id="chartsCard"><h2>Charts (live)</h2><div id="charts"></div></div>
<div class="card" style="margin-bottom:14px">
<h2>Rollups (live)</h2>
<div class="pillnav" id="rollnav"></div>
<div id="rollup"></div>
</div>
<div class="card" style="margin-bottom:14px">
<h2>Every product (live) — <span id="rowcount"></span></h2>
<div class="tablewrap"><table><thead><tr id="thead"></tr></thead><tbody id="tbody"></tbody></table></div>
</div>
<div class="card"><h2>Methodology</h2><div id="method"></div></div>
</div>
</div>
<footer>Self-contained. Recomputes in your browser; the numbers match the Python model at the saved assumptions. Clickt — clickt.ca/tools</footer>
</div>
<script>/*__VENDOR__*/</script>
<script id="data" type="application/json">__DATA__</script>
<script>
const MODEL = JSON.parse(document.getElementById("data").textContent);
const CUR = MODEL.provenance.currency || "";
const P = {
  ship: MODEL.params.ship, proc: MODEL.params.proc, fixed: MODEL.params.fixed,
  total_rev: MODEL.params.total_rev,
  exc: MODEL.params.cutoffs.exc, high: MODEL.params.cutoffs.high,
  avg: MODEL.params.cutoffs.avg, low: MODEL.params.cutoffs.low
};
const BANDS = ["Excellent","High","Average","Low","Poor","Inactive"];
const VCOGS = MODEL.vcogs || {};
const ROLLUP_DIMS = [["camp","By campaign"],["ven","By vendor"],["cat","By category"],["pt","By product type"],["pivot","Pivot"]];
let sortKey = "cm3", sortDir = -1;
let rollupDim = "camp";
// Pivot selections persist in module state so a slider drag (renderAll ->
// renderRollups -> renderPivot) refreshes only the matrix, never the dropdowns.
let pivotRow = "camp", pivotCol = "ven", pivotMeas = "cm3";

function money(v){if(v===null||v===undefined)return "—";const s=v<0?"-":"";return s+"$"+Math.round(Math.abs(v)).toLocaleString();}
function pct(v){return v===null||v===undefined?"—":(v*100).toFixed(1)+"%";}
function mult(v){return v===null||v===undefined?"—":v.toFixed(2)+"×";}
function intf(v){return v===null||v===undefined?"—":Math.round(v).toLocaleString();}
function esc(s){return String(s==null?"":s).replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));}

function calc(r){
  const varpct = r.cogs + P.ship + P.proc;
  const cm1 = r.rev * (1 - varpct);
  const cm2 = cm1 - r.cost;
  const fixed_alloc = (P.fixed > 0 && P.total_rev > 0) ? P.fixed * (r.rev / P.total_rev) : 0;
  const cm3 = cm2 - fixed_alloc;
  const cm3_pct = r.rev > 0 ? cm3 / r.rev : null;
  return {cm1, cm2, cm3, cm3_pct};
}
function bandOf(cm3_pct, rev, cost){
  if (rev <= 0 && cost <= 0) return "Inactive";
  if (rev <= 0) return "Poor";
  if (cm3_pct === null) return "Poor";
  if (cm3_pct >= P.exc) return "Excellent";
  if (cm3_pct >= P.high) return "High";
  if (cm3_pct >= P.avg) return "Average";
  if (cm3_pct >= P.low) return "Low";
  return "Poor";
}
function rowsComputed(){
  return MODEL.rows.map(r => {const c = calc(r); return {...r, ...c, band: bandOf(c.cm3_pct, r.rev, r.cost)};});
}

// --- Rollup aggregation (mirrors the Python Bucket: sums, cm3%=cm3/rev|null,
// roas=rev/cost|null; buckets first-seen order, then sorted by CM3 desc). ---
function newBucket(){return {n:0,impr:0,clicks:0,cost:0,conv:0,rev:0,cm1:0,cm2:0,cm3:0};}
function addTo(b,r){b.n++;b.impr+=r.impr;b.clicks+=r.clicks;b.cost+=r.cost;b.conv+=r.conv;b.rev+=r.rev;b.cm1+=r.cm1;b.cm2+=r.cm2;b.cm3+=r.cm3;}
function bCm3Pct(b){return b.rev>0?b.cm3/b.rev:null;}
function bRoas(b){return b.cost>0?b.rev/b.cost:null;}
function aggregate(rows,keyFn){const m=new Map();rows.forEach(r=>{const k=keyFn(r);if(k===null||k===undefined)return;if(!m.has(k))m.set(k,newBucket());addTo(m.get(k),r);});return m;}
function sortedBuckets(m){return [...m.entries()].sort((a,b)=>b[1].cm3-a[1].cm3);}
function totalCm3(rows){let s=0;rows.forEach(r=>s+=r.cm3);return s;}
function levelsPresent(rows,field){const out=[];for(let n=0;n<5;n++){let any=false;rows.forEach(r=>{if(r[field]&&r[field][n])any=true;});if(any)out.push(n);}return out;}
function bucketRow(name,b,tot,isVendor){
  return {name:name,n:b.n,impr:b.impr,clicks:b.clicks,conv:b.conv,cost:b.cost,rev:b.rev,
          roas:bRoas(b),cm3:b.cm3,cm3_pct:bCm3Pct(b),share:tot?b.cm3/tot:0,
          vcogs:isVendor?(VCOGS[name]!=null?VCOGS[name]:null):null};
}
// One structured rollup for a dimension. camp/ven -> {rows:[...]};
// cat/pt -> {levels:[{level, rows:[...]}]}. Used by the UI and the parity test.
function rollupData(dim){
  const rows=rowsComputed(), tot=totalCm3(rows);
  if(dim==="camp") return {rows:sortedBuckets(aggregate(rows,r=>r.camp)).map(([n,b])=>bucketRow(n,b,tot,false))};
  if(dim==="ven") return {rows:sortedBuckets(aggregate(rows,r=>r.ven?r.ven:null)).map(([n,b])=>bucketRow(n,b,tot,true))};
  const field=dim==="cat"?"catL":"ptL";
  return {levels:levelsPresent(rows,field).map(n=>({
    level:n+1,
    rows:sortedBuckets(aggregate(rows,r=>(r[field]&&r[field][n])?r[field][n]:"(unset)")).map(([nm,b])=>bucketRow(nm,b,tot,false))
  }))};
}

// --- Pivot cross-tab (sibling to rollupData; reuses the same bucket engine). ---
// Selectable dimensions: Campaign, Vendor, and every taxonomy level (already
// per-row on catL/ptL). Measures: CM3 $, CM3 %, Revenue, Ad spend, ROAS,
// Products. Ratio measures (cm3_pct/roas) are DERIVED per cell/total via the
// shared helpers, never summed.
const PIVOT_DIMS = [
  ["camp","Campaign"],["ven","Vendor"],
  ["catL0","Category L1"],["catL1","Category L2"],["catL2","Category L3"],["catL3","Category L4"],["catL4","Category L5"],
  ["ptL0","Product type L1"],["ptL1","Product type L2"],["ptL2","Product type L3"],["ptL3","Product type L4"],["ptL4","Product type L5"]
];
const PIVOT_MEASURES = [
  ["cm3","CM3 $","money"],["cm3_pct","CM3 %","pct"],["rev","Revenue","money"],
  ["cost","Ad spend","money"],["roas","ROAS","mult"],["n","Products","intf"]
];
// Missing keys map to "(unset)" so EVERY product lands in exactly one cell.
// This deliberately differs from the vendor rollup (rollupData("ven")), which
// SKIPS vendorless products; here a blank dim value becomes an explicit
// "(unset)" bucket so the cross-tab conserves the full product universe.
function pivotKey(r,dim){
  if(dim==="camp") return r.camp||"(unset)";
  if(dim==="ven") return r.ven?r.ven:"(unset)";
  const m=/^(catL|ptL)([0-4])$/.exec(dim);
  if(m){const arr=m[1]==="catL"?r.catL:r.ptL;const v=arr&&arr[+m[2]];return v?v:"(unset)";}
  return "(unset)";
}
function pivotMeasure(b,meas){
  if(meas==="cm3_pct") return bCm3Pct(b);
  if(meas==="roas") return bRoas(b);
  return b[meas]; // cm3 | rev | cost | n — summed on the bucket
}
function pivotFmt(v,type){
  if(type==="money") return money(v);
  if(type==="pct") return pct(v);
  if(type==="mult") return mult(v);
  return intf(v);
}
// Map<rowKey, Map<colKey, bucket>> + row/col/grand total buckets. Rows sorted
// by row-total[measure] desc, cols by col-total[measure] desc; capped to the
// top-12 x top-12, but ALL totals (row/col/grand) are computed over the full
// universe, so a column total need not equal the sum of its shown cells — the
// "…N more (in totals)" note flags that. Ratio measures sort nulls last.
function pivotData(rowDim,colDim,measure){
  const rows=rowsComputed();
  const cellB=new Map(), rowB=new Map(), colB=new Map(), grand=newBucket();
  rows.forEach(r=>{
    const rk=pivotKey(r,rowDim), ck=pivotKey(r,colDim);
    if(!cellB.has(rk)) cellB.set(rk,new Map());
    const cm=cellB.get(rk); if(!cm.has(ck)) cm.set(ck,newBucket()); addTo(cm.get(ck),r);
    if(!rowB.has(rk)) rowB.set(rk,newBucket()); addTo(rowB.get(rk),r);
    if(!colB.has(ck)) colB.set(ck,newBucket()); addTo(colB.get(ck),r);
    addTo(grand,r);
  });
  const mv=b=>pivotMeasure(b,measure);
  const key=(map,k)=>{const v=mv(map.get(k));return v==null?-Infinity:v;};
  const allRowKeys=[...rowB.keys()].sort((a,b)=>key(rowB,b)-key(rowB,a));
  const allColKeys=[...colB.keys()].sort((a,b)=>key(colB,b)-key(colB,a));
  const CAP=12;
  const rowKeys=allRowKeys.slice(0,CAP), colKeys=allColKeys.slice(0,CAP);
  const cell={}, rowTot={}, colTot={};
  rowKeys.forEach(rk=>{cell[rk]={};const cm=cellB.get(rk);
    colKeys.forEach(ck=>{cell[rk][ck]=cm.has(ck)?mv(cm.get(ck)):null;});
    rowTot[rk]=mv(rowB.get(rk));});
  colKeys.forEach(ck=>{colTot[ck]=mv(colB.get(ck));});
  return {measure,rowDim,colDim,rowKeys,colKeys,cell,rowTot,colTot,grand:mv(grand),
          extraRows:allRowKeys.length-rowKeys.length,extraCols:allColKeys.length-colKeys.length,
          nRows:allRowKeys.length,nCols:allColKeys.length};
}

const COLS = [
  ["t","Product","l"],["camp","Campaign","l"],["ven","Vendor","l"],
  ["cogs","COGS%","r"],["impr","Impr.","r"],["clicks","Clicks","r"],
  ["cost","Ad spend","r"],["conv","Conv.","r"],["rev","Revenue","r"],
  ["cm3","CM3","r"],["cm3_pct","CM3%","r"],["band","Band","l"]
];

function renderProv(){
  const p = MODEL.provenance;
  document.getElementById("prov").textContent =
    `${p.period} · ${p.currency} · ${p.n.toLocaleString()} products · COGS: ${p.cogs_mode} · generated ${p.generated}`;
}
function syncLabels(){
  document.getElementById("shipv").textContent = (P.ship*100).toFixed(1)+"%";
  document.getElementById("procv").textContent = (P.proc*100).toFixed(1)+"%";
  document.getElementById("excv").textContent = (P.exc*100).toFixed(1)+"%";
  document.getElementById("highv").textContent = (P.high*100).toFixed(1)+"%";
  document.getElementById("avgv").textContent = (P.avg*100).toFixed(1)+"%";
  document.getElementById("lowv").textContent = (P.low*100).toFixed(1)+"%";
}
function renderKpis(rows){
  let rev=0,cost=0,cm3=0;
  rows.forEach(r => {rev+=r.rev;cost+=r.cost;cm3+=r.cm3;});
  const cm3p = rev>0?cm3/rev:null, roas = cost>0?rev/cost:null;
  const k = [["Revenue",money(rev)],["Ad spend",money(cost)],["CM3",money(cm3)],["CM3 %",pct(cm3p)],["ROAS",mult(roas)]];
  document.getElementById("kpis").innerHTML = k.map(x=>`<div class="kpi"><div class="l">${x[0]}</div><div class="v">${x[1]}</div></div>`).join("");
}
function renderBands(rows){
  const bk = {}; BANDS.forEach(b=>bk[b]=newBucket()); rows.forEach(r=>addTo(bk[r.band],r));
  const tot = totalCm3(rows);
  const head = `<th class="l">Band</th><th>Products</th><th>Revenue</th><th>Ad spend</th><th>CM3</th><th>CM3 %</th><th>Share of CM3</th>`;
  const body = BANDS.map(b=>{const x=bk[b];const sh=tot?x.cm3/tot:0;
    return `<tr><td class="l"><span class="badge b-${b}">${b}</span></td><td>${x.n.toLocaleString()}</td>`
      +`<td>${money(x.rev)}</td><td>${money(x.cost)}</td><td>${money(x.cm3)}</td>`
      +`<td>${pct(bCm3Pct(x))}</td><td>${pct(sh)}</td></tr>`;}).join("");
  document.getElementById("bands").innerHTML =
    `<div class="tablewrap"><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div>`;
}
function renderSummaryKpis(rows){
  let impr=0,clicks=0,cost=0,conv=0,rev=0,cm1=0,cm2=0,cm3=0;
  rows.forEach(r=>{impr+=r.impr;clicks+=r.clicks;cost+=r.cost;conv+=r.conv;rev+=r.rev;cm1+=r.cm1;cm2+=r.cm2;cm3+=r.cm3;});
  const div=(a,b)=>b>0?a/b:null;
  const items=[
    ["Impressions",intf(impr)],["Clicks",intf(clicks)],["CTR",pct(div(clicks,impr))],
    ["Avg. CPC",money(div(cost,clicks))],["Conversions",intf(conv)],["Conv. rate",pct(div(conv,clicks))],
    ["Avg. order value",money(div(rev,conv))],["Cost / conv.",money(div(cost,conv))],["ROAS",mult(div(rev,cost))],
    ["CM1",money(cm1)],["CM1 %",pct(div(cm1,rev))],["CM2",money(cm2)],["CM2 %",pct(div(cm2,rev))],
    ["CM3",money(cm3)],["CM3 %",pct(div(cm3,rev))]
  ];
  document.getElementById("sumkpis").innerHTML = items.map(x=>`<div class="kr"><em>${x[0]}</em><b>${x[1]}</b></div>`).join("");
}
const _ROLL_STD = [["n","Products"],["impr","Impr."],["clicks","Clicks"],["conv","Conv."],["cost","Ad spend"],["rev","Revenue"],["roas","ROAS"],["cm3","CM3"],["cm3_pct","CM3 %"],["share","Share of CM3"]];
const _ROLL_VEN = [["n","Products"],["vcogs","COGS %"],["impr","Impr."],["clicks","Clicks"],["cost","Ad spend"],["rev","Revenue"],["roas","ROAS"],["cm3","CM3"],["cm3_pct","CM3 %"],["share","Share of CM3"]];
function rollCell(k,row){
  if(k==="vcogs"||k==="cm3_pct"||k==="share") return `<td>${pct(row[k])}</td>`;
  if(k==="roas") return `<td>${mult(row[k])}</td>`;
  if(k==="cost"||k==="rev"||k==="cm3") return `<td>${money(row[k])}</td>`;
  return `<td>${intf(row[k])}</td>`;
}
function rollTable(title,nameHdr,cols,rows){
  const head = `<th class="l">${esc(nameHdr)}</th>`+cols.map(c=>`<th>${c[1]}</th>`).join("");
  const body = rows.map(r=>`<tr><td class="l">${esc(r.name)}</td>`+cols.map(c=>rollCell(c[0],r)).join("")+`</tr>`).join("");
  return `<div class="rolltbl"><div class="rolltitle">${esc(title)}</div>`
    +`<div class="tablewrap"><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div></div>`;
}
function renderRollups(){
  const pillsync=()=>document.querySelectorAll("#rollnav .pill").forEach(p=>p.classList.toggle("on",p.dataset.dim===rollupDim));
  // Pivot mode: build the panel (selectors) ONCE; a re-render (slider drag)
  // refreshes only the matrix so the dropdowns keep their value + focus.
  if(rollupDim==="pivot"){
    if(document.getElementById("pivotPanel")) renderPivot(); else buildPivotPanel();
    pillsync();
    return;
  }
  let html="";
  if(rollupDim==="camp"){
    html = rollTable("By campaign","Campaign",_ROLL_STD,rollupData("camp").rows);
  } else if(rollupDim==="ven"){
    const d=rollupData("ven").rows;
    html = d.length ? rollTable("By vendor","Vendor",_ROLL_VEN,d)
                    : `<p class="muted">No vendor suffix found on the product titles in this CSV.</p>`;
  } else {
    const label = rollupDim==="cat"?"Category":"Product type";
    const lvls = rollupData(rollupDim).levels;
    html = lvls.length ? lvls.map(L=>rollTable(`${label} — Level ${L.level}`,`L${L.level} value`,_ROLL_STD,L.rows)).join("")
                       : `<p class="muted">No ${label.toLowerCase()} data in this CSV.</p>`;
  }
  document.getElementById("rollup").innerHTML = html;
  pillsync();
}
function buildPivotPanel(){
  const dimOpts=PIVOT_DIMS.map(d=>`<option value="${d[0]}">${esc(d[1])}</option>`).join("");
  const measOpts=PIVOT_MEASURES.map(m=>`<option value="${m[0]}">${esc(m[1])}</option>`).join("");
  document.getElementById("rollup").innerHTML =
    `<div id="pivotPanel"><div class="pivotctls">`
    +`<label class="pivotsel">Rows<select id="pivotRow">${dimOpts}</select></label>`
    +`<label class="pivotsel">Columns<select id="pivotCol">${dimOpts}</select></label>`
    +`<label class="pivotsel">Measure<select id="pivotMeas">${measOpts}</select></label>`
    +`</div><div id="pivotMatrix"></div></div>`;
  const rs=document.getElementById("pivotRow"), cs=document.getElementById("pivotCol"), ms=document.getElementById("pivotMeas");
  rs.value=pivotRow; cs.value=pivotCol; ms.value=pivotMeas;
  rs.addEventListener("change",()=>{pivotRow=rs.value;renderPivot();});
  cs.addEventListener("change",()=>{pivotCol=cs.value;renderPivot();});
  ms.addEventListener("change",()=>{pivotMeas=ms.value;renderPivot();});
  renderPivot();
}
function renderPivot(){
  const mx=document.getElementById("pivotMatrix"); if(!mx) return;
  const meas=PIVOT_MEASURES.find(m=>m[0]===pivotMeas)||PIVOT_MEASURES[0];
  const fmt=v=>pivotFmt(v,meas[2]);
  const d=pivotData(pivotRow,pivotCol,pivotMeas);
  if(!d.rowKeys.length){mx.innerHTML=`<p class="muted">No products to pivot.</p>`;return;}
  const head=`<th class="rowhdr">${esc(meas[1])}</th>`
    +d.colKeys.map(ck=>`<th>${esc(ck)}</th>`).join("")
    +`<th class="totcol">Total</th>`;
  const body=d.rowKeys.map(rk=>{
    const cells=d.colKeys.map(ck=>{const v=d.cell[rk][ck];
      return `<td class="${v==null?'dim':''}">${fmt(v)}</td>`;}).join("");
    return `<tr><td class="rowhdr">${esc(rk)}</td>${cells}<td class="totcol">${fmt(d.rowTot[rk])}</td></tr>`;
  }).join("");
  const totrow=`<tr class="totrow"><td class="rowhdr">Total</td>`
    +d.colKeys.map(ck=>`<td class="totcol">${fmt(d.colTot[ck])}</td>`).join("")
    +`<td class="totcol">${fmt(d.grand)}</td></tr>`;
  let note="";
  if(d.extraRows||d.extraCols){
    const parts=[];
    if(d.extraRows) parts.push(d.extraRows+" more row"+(d.extraRows>1?"s":""));
    if(d.extraCols) parts.push(d.extraCols+" more column"+(d.extraCols>1?"s":""));
    note=`<p class="muted">Showing top ${d.rowKeys.length}×${d.colKeys.length} by ${esc(meas[1])}. …${parts.join(" and ")} folded into the totals (totals span the full universe).</p>`;
  }
  mx.innerHTML=`<div class="tablewrap"><table class="pivttbl"><thead><tr>${head}</tr></thead>`
    +`<tbody>${body}${totrow}</tbody></table></div>`+note;
}
function renderMethod(){
  const pv=MODEL.provenance, sm=MODEL.srcmix||{};
  const keys=Object.keys(sm);
  const smLine = keys.length ? keys.map(k=>`${esc(k)}: ${sm[k].toLocaleString()}`).join(" · ") : "—";
  document.getElementById("method").innerHTML =
    `<div class="mrow"><em>CM3 formula</em><b>Revenue × (1 − COGS% − Shipping% − Processing%) − Ad spend − allocated fixed</b></div>`
   +`<div class="mrow"><em>COGS mode</em><b>${esc(pv.cogs_mode)}</b></div>`
   +`<div class="mrow"><em>COGS source mix (products)</em><b>${smLine}</b></div>`
   +`<div class="mrow"><em>Currency · period</em><b>${esc(pv.currency)} · ${esc(pv.period)}</b></div>`
   +`<div class="mrow"><em>Products</em><b>${pv.n.toLocaleString()}</b></div>`
   +`<p class="muted">Assumptions in the panel are live — every KPI, band, chart, rollup and row on this page recomputes as you change them. Bands read CM3% (CM3 ÷ revenue) against the cutoffs: Excellent, then High, Average, Low; below Low is Poor. A product with $0 revenue and $0 ad spend is Inactive; $0 revenue with ad spend is forced to Poor. Share of CM3 is a bucket's CM3 as a fraction of total CM3.</p>`;
}
function renderTable(rows){
  document.getElementById("rowcount").textContent = rows.length.toLocaleString() + " rows";
  document.getElementById("thead").innerHTML = COLS.map(c=>
    `<th class="${c[2]==='l'?'l':''}" data-k="${c[0]}">${c[1]}</th>`).join("");
  const sorted = rows.slice().sort((a,b)=>{
    let x=a[sortKey], y=b[sortKey];
    if(typeof x==="string"){x=x||"";y=y||"";return sortDir*x.localeCompare(y);}
    x=x==null?-Infinity:x; y=y==null?-Infinity:y; return sortDir*(x-y);
  });
  document.getElementById("tbody").innerHTML = sorted.map(r=>{
    const c = COLS.map(col=>{
      const k = col[0];
      if(k==="band") return `<td class="l"><span class="badge b-${r.band}">${r.band}</span></td>`;
      if(k==="t"||k==="camp"||k==="ven") return `<td class="l">${esc(r[k])}</td>`;
      if(k==="cogs"||k==="cm3_pct") return `<td>${pct(r[k])}</td>`;
      if(k==="cost"||k==="rev"||k==="cm3") return `<td>${money(r[k])}</td>`;
      return `<td>${Math.round(r[k]).toLocaleString()}</td>`;
    }).join("");
    return `<tr>${c}</tr>`;
  }).join("");
  document.querySelectorAll("#thead th").forEach(th=>th.addEventListener("click",()=>{
    const k=th.dataset.k; if(sortKey===k) sortDir*=-1; else {sortKey=k;sortDir=-1;} renderAll();
  }));
}
function renderAll(){
  const rows = rowsComputed();
  renderKpis(rows); renderSummaryKpis(rows); renderBands(rows); renderTable(rows); renderRollups(); syncLabels();
}
function setupRollnav(){
  document.getElementById("rollnav").innerHTML = ROLLUP_DIMS.map(d=>
    `<button class="pill" data-dim="${d[0]}">${d[1]}</button>`).join("");
  document.querySelectorAll("#rollnav .pill").forEach(p=>p.addEventListener("click",()=>{
    rollupDim = p.dataset.dim; renderRollups();
  }));
}
function bind(id, key, scale){
  const el = document.getElementById(id);
  el.value = key==="fixed" ? P.fixed : (P[key] * (scale||1));
  const setP=()=>{if(el.type==="range"){const span=(+el.max - +el.min)||1; el.style.setProperty('--p',((+el.value - +el.min)/span)*100);}};
  setP();
  el.addEventListener("input", ()=>{P[key] = key==="fixed" ? parseFloat(el.value||0) : parseFloat(el.value)/(scale||1); setP(); renderAll();});
}
// ── Theme (light/dark). Stamps data-theme on :root; the three-layer CSS above
// resolves the rest. matchMedia is guarded so jsdom (which lacks it) never throws.
// Charts register window.__cm3ThemeHook to re-mount their Vega views on toggle.
function effTheme(){
  const set=document.documentElement.getAttribute("data-theme");
  if(set==="dark"||set==="light") return set;
  if(typeof matchMedia==="function" && matchMedia("(prefers-color-scheme: dark)").matches) return "dark";
  return "light";
}
function updateThemeBtn(){
  const dark=effTheme()==="dark";
  const ico=document.getElementById("themeIco"), txt=document.getElementById("themeTxt");
  if(ico) ico.textContent = dark ? "☀" : "☾";
  if(txt) txt.textContent = dark ? "Light" : "Dark";
}
function applyTheme(t){
  document.documentElement.setAttribute("data-theme", t);
  try{localStorage.setItem("cm3-theme", t);}catch(e){}
  updateThemeBtn();
  if(typeof window.__cm3ThemeHook==="function") window.__cm3ThemeHook();
}
(function initTheme(){
  let saved=null; try{saved=localStorage.getItem("cm3-theme");}catch(e){}
  if(saved==="dark"||saved==="light") document.documentElement.setAttribute("data-theme", saved);
  updateThemeBtn();
  const btn=document.getElementById("themeToggle");
  if(btn) btn.addEventListener("click", ()=>applyTheme(effTheme()==="dark"?"light":"dark"));
})();
renderProv();
setupRollnav();
renderMethod();
bind("ship","ship",100); bind("proc","proc",100); bind("fixed","fixed",1);
bind("exc","exc",100); bind("high","high",100); bind("avg","avg",100); bind("low","low",100);
renderAll();
/*__CHARTS__*/
</script>
</body>
</html>
"""


# Chart hooks in _TEMPLATE; stripped whole when charts are disabled so a
# chartless render carries no vendor bytes and no chart chrome.
_VENDOR_LINE = "<script>/*__VENDOR__*/</script>\n"
_CHARTS_CARD_LINE = ('<div class="card" style="margin-bottom:14px" id="chartsCard">'
                     '<h2>Charts (live)</h2><div id="charts"></div></div>\n')
_CHARTS_JS_LINE = "/*__CHARTS__*/\n"

# Injected only when charts are enabled. Runs at the end of the main script:
# builds one live view per spec (all reading the named dataset "rows"), then
# chains chart refresh onto the existing renderAll() recompute loop. The rows
# pushed to the charts come from the same rowsComputed() as the table (base
# rows + cm3/cm3_pct/band), so the live charts and the static SVGs agree at
# the default parameters. The changeset form is required — the view.data
# setter does not reliably propagate through Vega-Lite's derived datasets.
_CHARTS_JS = """\
const chartViews = [];
// Dark-mode Vega config (NOVEL — the audits use GSAP, not Vega, so there is no
// in-repo prior art). Only the LIVE explorer views get this; the static md SVGs
// (render_static_charts / vl_convert) are a separate, themeless-light path and
// are never touched here. Text -> light, gridlines -> dim, background -> transparent.
function chartCfg(dark){
  return dark ? {
    background:"transparent", view:{stroke:"transparent"},
    axis:{labelColor:"#C9D1D9",titleColor:"#E6EDF3",gridColor:"rgba(238,241,243,.10)",domainColor:"rgba(238,241,243,.22)",tickColor:"rgba(238,241,243,.22)"},
    legend:{labelColor:"#C9D1D9",titleColor:"#E6EDF3"},
    title:{color:"#E6EDF3",subtitleColor:"#C9D1D9"}
  } : {
    background:"transparent", view:{stroke:"transparent"},
    axis:{labelColor:"#5C6470",titleColor:"#0B0F0E",gridColor:"rgba(11,15,14,.08)",domainColor:"rgba(11,15,14,.18)",tickColor:"rgba(11,15,14,.18)"},
    legend:{labelColor:"#5C6470",titleColor:"#0B0F0E"},
    title:{color:"#0B0F0E"}
  };
}
function isDarkTheme(){
  if(typeof effTheme==="function") return effTheme()==="dark";
  const set=document.documentElement.getAttribute("data-theme");
  if(set==="dark"||set==="light") return set==="dark";
  return typeof matchMedia==="function" && matchMedia("(prefers-color-scheme: dark)").matches;
}
// Live charts fill the card: override width with the container's measured width
// (numeric, so it works with the minimal vendored embed shim — no reliance on
// Vega "container" sizing). The STATIC md SVGs keep their fixed 560 from CHARTS.
function liveWidth(){const h=document.getElementById("charts");const w=h?h.clientWidth:0;return w>60?w:560;}
function themedSpec(sp){const s=Object.assign({},sp);s.background="transparent";s.width=liveWidth();s.autosize={type:"fit",contains:"padding"};s.config=chartCfg(isDarkTheme());return s;}
function mountCharts(){
  const host=document.getElementById("charts"); if(!host) return;
  host.innerHTML=""; chartViews.length=0;
  CHARTS.forEach((sp,i)=>{const box=document.createElement("div");box.id="chart_"+i;box.style.margin="0 0 14px";host.appendChild(box);chartViews.push(vlEmbed(box,themedSpec(sp)));const s=box.querySelector("svg");if(s){s.style.overflow="visible";s.style.maxWidth="100%";}});
}
function renderCharts(){const rows=rowsComputed();chartViews.forEach(v=>v.change("rows",vega.changeset().remove(()=>true).insert(rows)).run());}
// Re-mount with the new theme config, then repopulate rows, when the header toggle fires.
window.__cm3ThemeHook=function(){mountCharts();renderCharts();};
const __renderAllBase=renderAll;renderAll=function(){__renderAllBase();renderCharts();};
// Re-fit to the container on resize (debounced).
var __cm3rz;window.addEventListener("resize",function(){clearTimeout(__cm3rz);__cm3rz=setTimeout(function(){mountCharts();renderCharts();},160);});
mountCharts();
renderCharts();"""


def render_html(ctx: dict, period: str | None, currency: str, *, charts: bool = True) -> str:
    data = json.dumps(_model(ctx, period, currency), ensure_ascii=False)
    data = data.replace("</", "<\\/")
    html = _TEMPLATE.replace("__DATA__", data)
    if charts and CHARTS:
        html = html.replace("/*__VENDOR__*/", _charts.vendor_blob())
        html = html.replace("/*__CHARTS__*/",
                            "const CHARTS = " + _charts.charts_json({"charts": CHARTS}) + ";\n"
                            + _CHARTS_JS)
    else:
        html = html.replace(_VENDOR_LINE, "")
        html = html.replace(_CHARTS_CARD_LINE, "")
        html = html.replace(_CHARTS_JS_LINE, "")
    return html


def build_html(ctx: dict, period: str | None, currency: str, output_path: str, *,
               charts: bool = True) -> None:
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(render_html(ctx, period, currency, charts=charts))


# ─── In-Claude tuner fragment ───────────────────────────────────────────────────
# A show_widget HTML fragment (NOT a standalone page) that reuses the same recompute
# kernel as the explorer above, exposes it under the shared tuner's DOM conventions
# (#gx-controls/.gx-ctl/gv_<key>, globals MODEL/SPEC/P + summarize/classify), and adds
# an Outputs card whose Save/Export buttons sendPrompt a one-shot rebuild via
# cm3_by_product.py at the tuned params. Host theme vars only; zero external refs.

def _widget_summary(ctx: dict) -> dict:
    """KPI summary mirrored by the JS summarize() — totals + per-band counts."""
    t = ctx["totals"]
    bb = ctx["by_band"]
    rev, cost, cm3 = t.conv_value, t.cost, t.cm3
    return {
        "total_rev": rev, "total_cost": cost, "total_cm3": cm3,
        "cm3_pct": (cm3 / rev) if rev > 0 else None,
        "roas": (rev / cost) if cost > 0 else None,
        "n_excellent": bb["Excellent"].n_products,
        "n_high": bb["High"].n_products,
        "n_avg": bb["Average"].n_products,
        "n_low": bb["Low"].n_products,
        "n_poor": bb["Poor"].n_products,
        "n_inactive": bb["Inactive"].n_products,
    }


def _widget_model(ctx: dict, period: str | None, currency: str,
                  brand: str | None, csv_path: str | None, cogs_csv: str | None) -> dict:
    base = _model(ctx, period, currency)   # provenance + rows (reused, no row loss)
    inp = ctx["inputs"]
    cut = _cutoffs(ctx)
    total_rev = base["params"]["total_rev"]
    params = {
        "cogs": inp["cogs_pct"] / 100.0,
        "ship": inp["ship_pct"] / 100.0,
        "proc": inp["proc_pct"] / 100.0,
        "fixed": float(inp.get("fixed_costs") or 0),
        "total_rev": total_rev,
        "exc": cut["exc"], "high": cut["high"], "avg": cut["avg"], "low": cut["low"],
    }
    prov = dict(base["provenance"])
    prov["title"] = "CM3 by product" + (f" — {period}" if period else "")
    date = _dt.date.today().isoformat()
    slug = re.sub(r"[^a-z0-9]+", "-", (brand or "").lower()).strip("-")
    stem = "cm3-by-product" + (("_" + slug) if slug else "") + "_" + date
    save = {
        "skill": "cm3-by-product-report",
        "brand": brand or "CM3 by product",
        "filename_stem": stem,
        "csv": csv_path or "",
        "cogs_csv": cogs_csv or "",
    }
    return {"provenance": prov, "params": params,
            "summary": _widget_summary(ctx), "rows": base["rows"], "save": save}


def _widget_charts_card(ctx: dict) -> str:
    """Static widget-flagged chart SVG(s) rendered at the report defaults,
    wrapped in a card. Generated through the vendored chart module — never
    hand-authored. Empty string when no chart carries widget=True."""
    rendered = render_static_charts(ctx, only="widget")
    if not rendered:
        return ""
    parts = ['<div class="cx-card"><h2>Charts</h2>']
    for cid, _title, svg in rendered:
        parts.append(f'<div class="cx-chart" id="cxc_{cid}">{svg}</div>')
    parts.append('<div class="cx-note">Shown at the report defaults — '
                 'Save/Export rebuilds every output at your tuned settings.</div></div>')
    return "".join(parts)


_WIDGET_CHARTS_MARK = "<!--__CHARTS_CARD__-->"


def build_widget_fragment(ctx: dict, period: str | None, currency: str, *,
                          brand: str | None = None, csv_path: str | None = None,
                          cogs_csv: str | None = None, charts: bool = True) -> str:
    data = json.dumps(_widget_model(ctx, period, currency, brand, csv_path, cogs_csv),
                      ensure_ascii=False).replace("</", "<\\/")
    frag = _WIDGET_TEMPLATE.replace("/*__DATA__*/", data)
    card = _widget_charts_card(ctx) if charts else ""
    return frag.replace("  " + _WIDGET_CHARTS_MARK + "\n", ("  " + card + "\n") if card else "")


_WIDGET_TEMPLATE = r"""<style>
.cx-prov{color:var(--text-muted);font-size:12px;margin:0 0 10px}
.cx-about{font-size:12px;color:var(--text-secondary);line-height:1.5;margin:0 0 12px}
.cx-about .sum{margin:0 0 8px}
.cx-about .leg{display:flex;flex-direction:column;gap:5px}
.cx-about .leg .r{display:flex;gap:8px;align-items:baseline}
.cx-about .leg .badge{flex:0 0 auto;align-self:flex-start}
.cx-about .leg .d{color:var(--text-muted)}
/* Clickt HiveMind brand accent (teal #1F7A82) — scoped to the widget so only the accent + accent-tint change; surfaces/text stay on the Claude host theme (light/dark adaptive). */
.cx-brand{--text-accent:#1F7A82;--bg-accent:#DAE9E6}
@media(prefers-reduced-motion:reduce){.cx-brand *{transition:none!important}}
.cx-card{background:var(--surface-1);border-radius:12px;padding:12px 14px;margin:0 0 12px}
.cx-card h2{font-size:12px;margin:0 0 10px;font-weight:500;text-transform:uppercase;letter-spacing:.04em;color:var(--text-secondary)}
.cx-ctls{display:grid;grid-template-columns:1fr 1fr;gap:14px 16px}
.gx-ctl label{display:flex;justify-content:space-between;align-items:center;font-size:12px;color:var(--text-secondary);margin:0 0 6px}
.gx-ctl .v{display:inline-block;min-width:2.4em;padding:1px 8px;border-radius:999px;background:var(--bg-accent);color:var(--text-accent);font-weight:600;font-size:11px;font-variant-numeric:tabular-nums;text-align:center}
.gx-ctl input[type=range]{-webkit-appearance:none;appearance:none;width:100%;height:16px;margin:6px 0;background:transparent;cursor:pointer}
.gx-ctl input[type=range]::-webkit-slider-runnable-track{height:6px;border-radius:999px;background:linear-gradient(90deg,var(--text-accent) 0 calc(var(--p,0)*1%),var(--border) calc(var(--p,0)*1%) 100%)}
.gx-ctl input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;appearance:none;width:16px;height:16px;margin-top:-5px;border-radius:50%;background:var(--surface-1);border:2px solid var(--text-accent);box-shadow:0 1px 2px rgba(0,0,0,.25);transition:box-shadow .15s,transform .15s}
.gx-ctl input[type=range]::-moz-range-track{height:6px;border-radius:999px;background:var(--border)}
.gx-ctl input[type=range]::-moz-range-progress{height:6px;border-radius:999px;background:var(--text-accent)}
.gx-ctl input[type=range]::-moz-range-thumb{width:16px;height:16px;border:2px solid var(--text-accent);border-radius:50%;background:var(--surface-1);box-shadow:0 1px 2px rgba(0,0,0,.25);transition:box-shadow .15s,transform .15s}
.gx-ctl input[type=range]:hover::-webkit-slider-thumb{transform:scale(1.08)}.gx-ctl input[type=range]:hover::-moz-range-thumb{transform:scale(1.08)}
.gx-ctl input[type=range]:active::-webkit-slider-thumb{transform:scale(1.12)}.gx-ctl input[type=range]:active::-moz-range-thumb{transform:scale(1.12)}
.gx-ctl input[type=range]:focus{outline:none}
.gx-ctl input[type=range]:focus-visible::-webkit-slider-thumb{box-shadow:0 0 0 4px color-mix(in srgb,var(--text-accent) 30%,transparent)}
.gx-ctl input[type=range]:focus-visible::-moz-range-thumb{box-shadow:0 0 0 4px color-mix(in srgb,var(--text-accent) 30%,transparent)}
.gx-ctl input[type=number]{width:120px;height:30px;padding:0 8px;border:0.5px solid var(--border);border-radius:7px;background:var(--surface-2);color:var(--text-primary);font:inherit;font-size:12px;line-height:30px;font-variant-numeric:tabular-nums;transition:border-color .15s,box-shadow .15s}
.gx-ctl input[type=number]:focus{outline:none;border-color:var(--text-accent);box-shadow:0 0 0 3px color-mix(in srgb,var(--text-accent) 22%,transparent)}
:focus-visible{outline:2px solid var(--text-accent);outline-offset:2px}
th:focus-visible{outline-offset:-2px}
.cx-kpis{display:flex;flex-wrap:wrap;gap:10px}
.cx-kpi{flex:1;min-width:96px;background:var(--surface-2);border-radius:8px;padding:8px 10px}
.cx-kpi .n{font-size:20px;font-weight:500}
.cx-kpi .l{font-size:11px;color:var(--text-muted)}
.cx-bands{display:flex;flex-wrap:wrap;gap:8px}
.cx-bandstat{background:var(--surface-2);border-radius:8px;padding:6px 10px;font-size:12px}
.cx-chart{overflow-x:auto;margin:0 0 8px}
.cx-chart svg{overflow:visible;max-width:100%;height:auto}
.cx-tablewrap{overflow:auto;max-height:360px;border:0.5px solid var(--border);border-radius:8px}
table{width:100%;border-collapse:collapse;font-size:12px}
th,td{padding:5px 8px;border-bottom:0.5px solid var(--border);text-align:left;white-space:nowrap}
td.num,th.num{text-align:right}
th{position:sticky;top:0;background:var(--surface-2);cursor:pointer}
.badge{display:inline-block;padding:1px 8px;border-radius:999px;font-size:11px;font-weight:500}
.b-success{background:var(--bg-success);color:var(--text-success)}
.b-danger{background:var(--bg-danger);color:var(--text-danger)}
.b-warning{background:var(--bg-warning);color:var(--text-warning)}
.b-accent{background:var(--bg-accent);color:var(--text-accent)}
.b-neutral{background:var(--surface-2);color:var(--text-secondary)}
.cx-save{display:flex;gap:12px;align-items:center;flex-wrap:wrap}
.cx-save button{min-width:180px}
.cx-note{color:var(--text-muted);font-size:12px;margin-top:6px}
</style>
<div class="cx-brand" style="padding:1rem 0;max-width:100%">
  <div id="cx-title" style="font-size:16px;font-weight:500;margin:0 0 2px"></div>
  <div class="cx-prov" id="cx-prov"></div>
  <div class="cx-about" id="cx-about"></div>
  <div class="cx-card"><h2>Assumptions &amp; band cutoffs</h2><div class="cx-ctls" id="gx-controls"></div></div>
  <div class="cx-card"><h2>Results (live)</h2><div class="cx-kpis" id="cx-kpis"></div></div>
  <div class="cx-card"><h2>Band distribution</h2><div class="cx-bands" id="cx-bands"></div></div>
  <!--__CHARTS_CARD__-->
  <div class="cx-card"><h2 id="cx-tablehead">Products (live preview)</h2>
    <div class="cx-tablewrap"><table><thead id="cx-thead"></thead><tbody id="cx-tbody"></tbody></table></div>
    <div class="cx-note" id="cx-tcount"></div>
  </div>
  <div class="cx-card"><h2>Outputs</h2>
    <div class="cx-save">
      <button id="gx-save" type="button"><i class="ti ti-database-export" aria-hidden="true" style="font-size:16px;vertical-align:-2px;margin-right:6px"></i>Save to HiveMind ↗</button>
      <button id="gx-xlsx" type="button"><i class="ti ti-table" aria-hidden="true" style="font-size:16px;vertical-align:-2px;margin-right:6px"></i>Export Excel ↗</button>
      <button id="gx-html" type="button"><i class="ti ti-chart-dots" aria-hidden="true" style="font-size:16px;vertical-align:-2px;margin-right:6px"></i>Download HTML ↗</button>
      <button id="gx-pptx" type="button"><i class="ti ti-presentation" aria-hidden="true" style="font-size:16px;vertical-align:-2px;margin-right:6px"></i>Export PowerPoint ↗</button>
    </div>
    <div class="cx-note" id="cx-savenote"></div>
    <div class="cx-note" id="cx-savestate" style="min-height:14px"></div>
  </div>
</div>
<script id="cx-data" type="application/json">/*__DATA__*/</script>
<script>
const MODEL = JSON.parse(document.getElementById("cx-data").textContent);
const SAVE = MODEL.save;
const CUR = (MODEL.provenance && MODEL.provenance.currency) || "";
const ROW_CAP = 50;
const P = Object.assign({}, MODEL.params || {});
const SPEC = {
  title: (MODEL.provenance && MODEL.provenance.title) || "CM3 by product",
  row_noun: "products",
  controls: [
    {key:"cogs", label:"COGS % (fallback)", kind:"slider", min:0,    max:0.95, step:0.005},
    {key:"ship", label:"Shipping %",        kind:"slider", min:0,    max:0.60, step:0.005},
    {key:"proc", label:"Processing %",      kind:"slider", min:0,    max:0.15, step:0.001},
    {key:"fixed",label:"Fixed costs",       kind:"number", min:0,    step:100},
    {key:"exc",  label:"Excellent ≥",       kind:"slider", min:0,    max:0.40, step:0.005},
    {key:"high", label:"High ≥",            kind:"slider", min:0,    max:0.30, step:0.005},
    {key:"avg",  label:"Average ≥",         kind:"slider", min:-0.10,max:0.20, step:0.005},
    {key:"low",  label:"Low ≥",             kind:"slider", min:-0.60,max:0.10, step:0.005},
  ],
  kpis: [
    {key:"total_rev",  label:"Revenue",  money:true},
    {key:"total_cost", label:"Ad spend", money:true},
    {key:"total_cm3",  label:"CM3",      money:true},
    {key:"cm3_pct",    label:"CM3 %",    pct:true},
    {key:"roas",       label:"ROAS",     mult:true},
  ],
  columns: [
    {key:"t",      label:"Product"},
    {key:"camp",   label:"Campaign"},
    {key:"ven",    label:"Vendor"},
    {key:"cogs",   label:"COGS%",    fmt:"pct",   num:true},
    {key:"cost",   label:"Ad spend", fmt:"money", num:true},
    {key:"rev",    label:"Revenue",  fmt:"money", num:true},
    {key:"cm3",    label:"CM3",      fmt:"money", num:true},
    {key:"cm3_pct",label:"CM3%",     fmt:"pct",   num:true},
    {key:"band",   label:"Band",     fmt:"band"},
  ],
};
const FRAC = {cogs:1, ship:1, proc:1, exc:1, high:1, avg:1, low:1};   // pct-display controls
const BANDS = ["Excellent","High","Average","Low","Poor","Inactive"];
const BAND_CLS = {Excellent:"b-success",High:"b-success",Average:"b-accent",Low:"b-warning",Poor:"b-danger",Inactive:"b-neutral"};

const money = v => (v==null?"—":(v<0?"-":"")+"$"+Math.round(Math.abs(v)).toLocaleString()+(CUR?(" "+CUR):""));
const pct = v => (v==null?"—":(Number(v)*100).toFixed(1)+"%");
const mult = v => (v==null?"—":Number(v).toFixed(2)+"×");
const esc = s => String(s==null?"":s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function el(tag,attrs,html){const e=document.createElement(tag); if(attrs)for(const k in attrs)e.setAttribute(k,attrs[k]); if(html!=null)e.innerHTML=html; return e;}
function ctlReadout(key){const v=P[key]; if(key in FRAC){const n=Math.round(v*1000)/10; return (Number.isInteger(n)?String(n):n.toFixed(1))+"%";} return money(v);}

function calc(r,P){
  const cogs = (r.src==="Input") ? P.cogs : r.cogs;
  const varpct = cogs + P.ship + P.proc;
  const cm1 = r.rev * (1 - varpct);
  const cm2 = cm1 - r.cost;
  const fixed_alloc = (P.fixed>0 && P.total_rev>0) ? P.fixed * (r.rev/P.total_rev) : 0;
  const cm3 = cm2 - fixed_alloc;
  const cm3_pct = r.rev>0 ? cm3/r.rev : null;
  return {cm1,cm2,cm3,cm3_pct,cogs};
}
function bandOf(cm3_pct,rev,cost,P){
  if(rev<=0 && cost<=0) return "Inactive";
  if(rev<=0) return "Poor";
  if(cm3_pct===null) return "Poor";
  if(cm3_pct>=P.exc) return "Excellent";
  if(cm3_pct>=P.high) return "High";
  if(cm3_pct>=P.avg) return "Average";
  if(cm3_pct>=P.low) return "Low";
  return "Poor";
}
let classify = (r,P) => ({block: bandOf(calc(r,P).cm3_pct, r.rev, r.cost, P)});
let summarize = (rows,P) => {
  let rev=0,cost=0,cm3=0; const cnt={Excellent:0,High:0,Average:0,Low:0,Poor:0,Inactive:0};
  rows.forEach(r=>{const c=calc(r,P); const b=bandOf(c.cm3_pct,r.rev,r.cost,P); rev+=r.rev;cost+=r.cost;cm3+=c.cm3;cnt[b]++;});
  return {total_rev:rev,total_cost:cost,total_cm3:cm3,
    cm3_pct: rev>0?cm3/rev:null, roas: cost>0?rev/cost:null,
    n_excellent:cnt.Excellent,n_high:cnt.High,n_avg:cnt.Average,n_low:cnt.Low,n_poor:cnt.Poor,n_inactive:cnt.Inactive};
};

let sortKey="cm3", sortDir=-1;
function rowsComputed(){return (MODEL.rows||[]).map(r=>{const c=calc(r,P); return Object.assign({},r,c,{band:bandOf(c.cm3_pct,r.rev,r.cost,P)});});}

function renderProv(){
  const pr=MODEL.provenance||{};
  document.getElementById("cx-title").textContent = SPEC.title + " — tuner";
  document.getElementById("cx-tablehead").textContent = "Products (live preview)";
  const bits=[esc(pr.period||""), `currency ${esc(CUR||"—")}`, `${(MODEL.rows||[]).length.toLocaleString()} products`,
    `COGS: ${esc(pr.cogs_mode||"")}`, `generated ${esc(pr.generated||"—")}`];
  document.getElementById("cx-prov").textContent = bits.filter(Boolean).join(" · ");
  const ABOUT={
    summary:"Contribution margin after everything: CM3 = revenue − COGS − shipping − processing − ad spend − a share of fixed costs. Tune the cost assumptions and the band cutoffs to see how each product's margin and band move. Per-product COGS from your Shopify CSV is kept; the COGS slider is only a fallback for products without it.",
    legend:[
      {label:"Excellent",desc:"CM3% at or above the Excellent cutoff (default ≥ 10%)."},
      {label:"High",desc:"Between the High and Excellent cutoffs (default 5–10%)."},
      {label:"Average",desc:"Between the Average and High cutoffs (default 0–5%)."},
      {label:"Low",desc:"Between the Low and Average cutoffs (default −25–0%)."},
      {label:"Poor",desc:"Below the Low cutoff (default < −25%), or had ad spend but no revenue in the period."},
      {label:"Inactive",desc:"No revenue and no ad spend in the period — nothing to evaluate."}
    ]
  };
  document.getElementById("cx-about").innerHTML=`<div class="sum">${esc(ABOUT.summary)}</div><div class="leg">`+
    ABOUT.legend.map(L=>`<div class="r"><span class="badge ${BAND_CLS[L.label]||"b-neutral"}">${esc(L.label)}</span><span class="d">${esc(L.desc)}</span></div>`).join("")+`</div>`;
  document.getElementById("cx-savenote").textContent =
    "Save writes the markdown at the current settings into your vault (raw/reports/" + SAVE.filename_stem + ".md). Exports go to artifacts/.";
}
function renderControls(){
  const host=document.getElementById("gx-controls"); host.innerHTML="";
  const setP=(r,c)=>{const span=(c.max-c.min)||1; r.style.setProperty('--p',(((+r.value)-c.min)/span)*100);};
  (SPEC.controls||[]).forEach(c=>{
    const w=el("div",{class:"gx-ctl"});
    if(c.kind==="number"){
      w.innerHTML=`<label>${esc(c.label)} <span class="v" id="gv_${c.key}">${ctlReadout(c.key)}</span></label>`;
      const n=el("input",{type:"number",min:(c.min!=null?c.min:0),step:(c.step!=null?c.step:1),value:P[c.key]});
      n.oninput=()=>{P[c.key]=parseFloat(n.value||"0"); document.getElementById("gv_"+c.key).textContent=ctlReadout(c.key); renderAll();};
      w.appendChild(n);
    } else {
      w.innerHTML=`<label>${esc(c.label)} <span class="v" id="gv_${c.key}">${ctlReadout(c.key)}</span></label>`;
      const r=el("input",{type:"range",min:c.min,max:c.max,step:c.step,value:P[c.key]});
      setP(r,c);
      r.oninput=()=>{P[c.key]=parseFloat(r.value); document.getElementById("gv_"+c.key).textContent=ctlReadout(c.key); setP(r,c); renderAll();};
      w.appendChild(r);
    }
    host.appendChild(w);
  });
}
function renderKpis(){
  const S=summarize(MODEL.rows,P);
  document.getElementById("cx-kpis").innerHTML=(SPEC.kpis||[]).map(k=>{
    let v=S[k.key];
    if(k.money) v=money(v); else if(k.pct) v=pct(v); else if(k.mult) v=mult(v);
    return `<div class="cx-kpi"><div class="n">${v==null?"—":esc(v)}</div><div class="l">${esc(k.label)}</div></div>`;
  }).join("");
}
function renderBands(){
  const S=summarize(MODEL.rows,P);
  const map={Excellent:"n_excellent",High:"n_high",Average:"n_avg",Low:"n_low",Poor:"n_poor",Inactive:"n_inactive"};
  document.getElementById("cx-bands").innerHTML=BANDS.map(b=>
    `<div class="cx-bandstat"><span class="badge ${BAND_CLS[b]}">${b}</span> ${Number(S[map[b]]||0).toLocaleString()}</div>`).join("");
}
function fmtCell(r,col){
  if(col.fmt==="band") return `<span class="badge ${BAND_CLS[r.band]||"b-neutral"}">${esc(r.band)}</span>`;
  const v=r[col.key];
  if(col.fmt==="money") return money(v);
  if(col.fmt==="pct") return pct(v);
  return esc(v);
}
function renderTable(){
  const cols=SPEC.columns||[];
  let rows=rowsComputed();
  rows.sort((a,b)=>{let x=a[sortKey],y=b[sortKey];
    if(typeof x==="string"||typeof y==="string") return sortDir*String(x==null?"":x).localeCompare(String(y==null?"":y));
    return sortDir*((x==null?-Infinity:x)-(y==null?-Infinity:y));});
  const shown=rows.slice(0,ROW_CAP);
  document.getElementById("cx-thead").innerHTML="<tr>"+cols.map(c=>
    `<th class="${c.num?'num':''}" data-k="${c.key}">${esc(c.label)}${sortKey===c.key?(sortDir<0?' ▾':' ▴'):''}</th>`).join("")+"</tr>";
  document.getElementById("cx-tbody").innerHTML=shown.map(r=>
    "<tr>"+cols.map(col=>`<td class="${col.num?'num':''}">${fmtCell(r,col)}</td>`).join("")+"</tr>").join("");
  document.getElementById("cx-tcount").textContent =
    `Showing ${shown.length.toLocaleString()} of ${rows.length.toLocaleString()} — the full no-row-loss table is in the saved report and the on-disk explorer.`;
  document.querySelectorAll("#cx-thead th").forEach(th=>th.onclick=()=>{
    const k=th.dataset.k; if(sortKey===k)sortDir*=-1; else{sortKey=k;sortDir=-1;} renderTable();});
}
function renderAll(){renderKpis();renderBands();renderTable();}

function cliFlags(){
  const r6=n=>Math.round(n*1e6)/1e6;
  return `--cogs-pct ${r6(P.cogs*100)} --ship-pct ${r6(P.ship*100)} --proc-pct ${r6(P.proc*100)} `+
    `--fixed-costs ${r6(P.fixed)} --band-exc ${r6(P.exc)} --band-high ${r6(P.high)} `+
    `--band-avg ${r6(P.avg)} --band-low ${r6(P.low)}`;
}
function srcArgs(){return `--csv "${SAVE.csv}"`+(SAVE.cogs_csv?` --cogs-csv "${SAVE.cogs_csv}"`:"");}

document.getElementById("gx-save").addEventListener("click",()=>{
  document.getElementById("cx-savestate").textContent="Saving at the current settings…";
  sendPrompt(
    `Save the ${SAVE.brand} CM3-by-product report (${SAVE.skill}) to HiveMind at these tuned parameters: ${JSON.stringify(P)}. `+
    `Rebuild the markdown at exactly these params by running cm3_by_product.py on the original CSV: `+
    `${srcArgs()} ${cliFlags()} --output-md <vault>/raw/reports/${SAVE.filename_stem}.md (resolve <vault> with resolve_vault.py, `+
    `mkdir -p the raw/reports folder), writing it directly as ${SAVE.filename_stem}.md (overwrite if it already exists). `+
    `Do not propose_note and do not ask for approval — this is a direct save the operator authorized by clicking Save.`);
});
function gxExport(fmt,ext,label){
  document.getElementById("cx-savestate").textContent=label+" at the current settings…";
  sendPrompt(
    `Export the ${SAVE.brand} CM3-by-product report (${SAVE.skill}) as ${fmt} at these tuned parameters: ${JSON.stringify(P)}. `+
    `Rebuild from the original CSV by running cm3_by_product.py: ${srcArgs()} ${cliFlags()} `+
    `--output-${fmt} artifacts/${SAVE.filename_stem}.${ext}; then reply with the artifact path as a clickable markdown link. `+
    `Don't re-pull or change any data.`);
}
document.getElementById("gx-xlsx").addEventListener("click",()=>gxExport("xlsx","xlsx","Building the Excel workbook"));
document.getElementById("gx-html").addEventListener("click",()=>gxExport("html","html","Building the HTML explorer"));
document.getElementById("gx-pptx").addEventListener("click",()=>gxExport("pptx","pptx","Building the PowerPoint deck"));

renderProv();renderControls();renderAll();
</script>
"""
